---
- name: Install and Configure MySQL 8 on RHEL 9 and Replicate Configuration from Solaris
  hosts: all
  become: yes
  tasks:
    # Install MySQL 8 repository on RHEL 9
    - name: Install MySQL 8 repository
      yum:
        name: https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm
        state: present

    # Install MySQL 8
    - name: Install MySQL 8
      yum:
        name: mysql-community-server
        state: present

    # Start MySQL service on RHEL 9
    - name: Start MySQL service
      service:
        name: mysqld
        state: started
        enabled: yes

    # Get MySQL root password from the MySQL log
    - name: Get MySQL temporary root password
      shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
      register: mysql_root_password
      changed_when: false

    # Set the root password to Matilda@123
    - name: Set MySQL root password on RHEL 9
      community.mysql.mysql_user:
        name: root
        password: Matilda@123
        login_user: root
        login_password: "{{ mysql_root_password.stdout }}"
        host: localhost
        state: present
        authentication_plugin: mysql_native_password
      ignore_errors: yes

    # Disable MySQL password validation
    - name: Disable password validation
      community.mysql.mysql_query:
        login_user: root
        login_password: Matilda@123
        query: "SET GLOBAL validate_password_policy = LOW;"
      ignore_errors: yes

- name: Secure MySQL installation manually
  hosts: all
  become: yes
  tasks:
    - name: Remove anonymous users
      community.mysql.mysql_user:
        name: ""
        host_all: yes
        state: absent
        login_user: root
        login_password: Matilda@123

    - name: Disallow root login remotely
      community.mysql.mysql_query:
        query: "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"
        login_user: root
        login_password: Matilda@123

    - name: Remove test database
      community.mysql.mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: Matilda@123

    - name: Flush privileges
      community.mysql.mysql_query:
        query: "FLUSH PRIVILEGES;"
        login_user: root
        login_password: Matilda@123

- name: Dump and Restore MySQL Databases from Solaris to RHEL (MySQL 5.7 to MySQL 8)
  hosts: localhost
  tasks:
    - name: Dump MySQL databases from Solaris server
      shell: >
        sshpass -p "{{ solaris_server_password }}" ssh root@{{ solaris_mysql_host }} \
        "MYSQL_HOME={{ mysql_home_solaris }} {{ mysql_home_solaris }}/mysqldump -u {{ solaris_mysql_user }} -p{{ solaris_mysql_password }} --all-databases --single-transaction --quick --lock-tables=false > /tmp/mysql_dump.sql"
      delegate_to: localhost

    # Copy the dumped databases to RHEL
    - name: Copy MySQL dump from Solaris to RHEL
      copy:
        src: /tmp/mysql_dump.sql
        dest: /tmp/mysql_dump.sql

    # Import the dumped databases into MySQL on RHEL (MySQL 8)
    - name: Import databases into MySQL 8 on RHEL
      community.mysql.mysql_db:
        login_user: root
        login_password: Matilda@123
        state: import
        target: /tmp/mysql_dump.sql
      ignore_errors: yes

    # Set correct file permissions for MySQL on RHEL
    - name: Ensure correct file permissions for MySQL dump
      file:
        path: /tmp/mysql_dump.sql
        owner: mysql
        group: mysql
        mode: '0644'

    # Clean up the MySQL dump file
    - name: Clean up the MySQL dump file from RHEL
      file:
        path: /tmp/mysql_dump.sql
        state: absent
