- name: Create service accounts on RHEL 9
  hosts: n4
  become: yes
  tasks:
    - name: Create service groups
      group:
        name: "{{ item.group }}"
        gid: "{{ item.gid }}"
        state: present
      loop:
        - { group: 'apacheweb', gid: '1001' }
        - { group: 'weblogicapp', gid: '1002' }
        - { group: 'Mysqldb', gid: '1003' }

    - name: Create service accounts
      user:
        name: "{{ item.user }}"
        uid: "{{ item.uid }}"
        group: "{{ item.group }}"
        shell: /bin/bash
        home: "{{ item.home }}"
        create_home: yes
        state: present
      loop:
        - { user: 'apacheweb', uid: '1001', group: 'apacheweb', home: '/opt/apacheweb' }
        - { user: 'weblogicapp', uid: '1002', group: 'weblogicapp', home: '/opt/weblogicapp' }
        - { user: 'Mysqldb', uid: '1003', group: 'Mysqldb', home: '/opt/Mysqldb' }

    - name: Set permissions for home directories
      file:
        path: "{{ item.home }}"
        owner: "{{ item.user }}"
        group: "{{ item.group }}"
        mode: '0750'
        state: directory
      loop:
        - { user: 'apacheweb', group: 'apacheweb', home: '/opt/apacheweb' }
        - { user: 'weblogicapp', group: 'weblogicapp', home: '/opt/weblogicapp' }
        - { user: 'Mysqldb', group: 'Mysqldb', home: '/opt/Mysqldb' }
 
